# owlmaster
# Version 0.0
# Ansible Playbook - get pcap files from servers

- hosts: localhost

  tasks:
    - name: Find PCAP files.
      find:
        paths: "{{ pcaps_path }}"
      register: pcap_files

    - include_tasks: managesuricata.yaml pcap_file={{ item.path }}
      with_items:
        - "{{ pcap_files.files }}"
