# owlmaster
# Version 0.0
# Ansible Playbook - get pcap files from servers

- hosts: srvs

  vars:
    pcaps_path: "/var/owlh/traffic/"
    localpcaps_path: "/home/ec2-user/traffic/"
    period: "3"

  tasks:
    - name: Recursively find /tmp files older than 2 days
      find:
        paths: "{{ pcaps_path }}"
        age: "{{period}}"
      register: pcap_files

    - include_tasks: getanddelete.yaml pcap_file={{ item.path }}
      with_items:
        - "{{ pcap_files.files }}"
