# owlmaster
# Version 0.0
# Ansible Playbook - get pcap files from servers

- hosts: srvs

  tasks:
    - name: Recursively find /tmp files older than age period seconds
      find:
        paths: "{{ pcaps_path }}"
        age: "{{ period }}"
      register: pcap_files

    - include_tasks: getanddelete.yaml pcap_file={{ item.path }}
      with_items:
        - "{{ pcap_files.files }}"
