# owlmaster
# Version 0.0
# Ansible Playbook - run tcpdump on destination
# use -Z owlh with tcpdump command if you need to specify owlh user.

- hosts: srvs
  tasks:
    - name: start tcpdump
      shell: "(sudo tcpdump -i {{ ansible_default_ipv4.interface }} -G {{ period }} -w {{ pcaps_path }}$(hostname)-%y%m%d%H%M%S.pcap -F {{ filterpath }} &)"
      async: 10
      poll: 0
      become: true
      become_user: owl
      become_method: su
